# Services for mydocker environment
version: '3'
services:
  # MYSQL
  mysql:
    image: hub.babydev.de/base/mysql:5.7
    user: "1000:50"
    ports:
      - "3306:3306"
    networks:
      - mydockernet
    volumes:
      - ../application/mysql_data:/var/lib/mysql
    env_file:
      - ./env/mysql.env

  # PHP-FPM
  php-fpm:
    build: ./php
    image: mydocker/php-fpm:0.1.0
    volumes:
      - ../application:/var/www
    networks:
      - mydockernet
    ports:
      - "9000:9000"
    env_file:
      - ./env/symfony.env

  # NGINX
  nginx:
    build: ./nginx
    image: mydocker/nginx:0.1.0
    depends_on:
      - php-fpm
    networks:
      - mydockernet
    volumes:
      - ../application:/var/www
    ports:
      - "80:80"


# Use the dev environment services network
networks:
  mydockernet:
    driver: "bridge"