<?php

namespace AppBundle\Repository;

/**
 * GuestbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestbookRepository extends \Doctrine\ORM\EntityRepository
{
}
